version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - zip -g deployment_package.zip Code.py
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync dist/s3-lambda s3://devin-1993
      #- aws lambda update-function-code --function-name codebuild --zip-file fileb://deployment_package.zip
