version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - cd lib
      - zip -r9 ../deployment_package.zip
      - cd ..
      - zip -g deployment_package.zip /DynamoDB-Lambda/API-Lambda-DynamoDB.py
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws lambda update-function-code --function-name QueryTest --zip-file fileb://deployment_package.zip
