#!/usr/bin/env python3.9
import json
import boto3
from boto3.dynamodb.conditions import Key, Attr
dynamodb_client = boto3.client('dynamodb')
dynamodb = boto3.resource('dynamodb')

table = dynamodb.Table('Federation')

def lambda_handler(event, context): #This is what creates our function, this is needed in most lambdas. 
    response = table.query(
        KeyConditionExpression=Key('PlanetName').eq("Earth") 
    )
    items = response['Items'][0]
    responses = table.delete_item(
        Key=items
        )
    list_items=str(responses)
    print("Deleting: " + list_items)